# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    # - run: npm test

  deploy:
    # Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy to GitHub Pages
        if: success() # Deploy only if the build was successful
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main  # The branch to deploy to
          folder: ./app  # The folder to deploy (replace with your build folder if it's different)
          token: ${{ secrets.GITHUB_TOKEN }}  # Use the default GitHub token for authentication

#     name: Node.js CI

# on:
#   push:
#     branches:
#       - main
#       - 'release/*'
#   pull_request:
#     branches:
#       - main
#   # Optionally, run on schedule
#   # schedule:
#   #   - cron: '0 0 * * *'

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [14.x, 16.x, 18.x] # Define Node.js versions you want to test

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v2

#     - name: Set up Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'

#     - name: Install dependencies
#       run: npm install

#     - name: Run tests
#       run: npm test

#     - name: Build project (optional)
#       run: npm run build

#     # Optional: deploy to your server or cloud service, e.g., Vercel, Netlify, AWS, etc.
#     # - name: Deploy to production
#     #   run: npm run deploy
#     #   env:
#     #     NODE_ENV: production
